name: Rust Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # When run in the `ubuntu-latest` image, it will cause error.
        # The reason is that the `xi` package can not be found.
        # Hence, we'll add `ubuntu-latest` back after we find a way to solve this problem.
        os: [macos-latest, windows-latest]
        rust: [stable]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --verbose
